// This is the code generated by tailwindcss-to-rust tool.
pub(crate) mod generated;
// The wrapper for the generated code.
pub(crate) mod tailwind;

// You need to re-export the wrapper.
pub use tailwind::*;
