// This is the code generated by tailwindcss-to-rust tool.
pub(crate) mod generated;

// You need to re-export the generated structs, the macros, and the
// `ToOptionVecstring` trait.
pub(crate) use generated::{C, M};
// If you're using Dioxus you'll also want to re-export the `DC` macro.
pub(crate) use tailwindcss_to_rust_macros::{ToOptionVecString, C, M};
