exclude = [
  "target",
]

[commands.rustfmt]
type    = "both"
include = "**/*.rs"
cmd     = [ "rustfmt", "--edition", "2021" ]
lint_flags = "--check"
ok_exit_codes = 0
lint_failure_exit_codes = 1

[commands.clippy]
type = "both"
include = "**/*.rs"
invoke = "once"
path-args = "none"
working-dir = "root"
cmd = [
    "cargo",
    "clippy",
    "--color",
    "always",
    "--locked",
    "--all-targets",
    "--all-features",
    "--",
    "-D",
    "clippy::pedantic",
    "-D",
    "warnings",
]
tidy_flags = "--fix"
ok_exit_codes = 0
lint_failure_exit_codes = 101
expect_stderr = true
labels = ["default"]

[commands.prettier]
type    = "both"
include = [ "**/*.md", "**/*.js", "**/*.yml" ]
cmd     = "prettier"
lint_flags = "--check"
tidy_flags = "--write"
ok_exit_codes = 0
lint_failure_exit_codes = 1

[commands.omegasort-gitignore]
type = "both"
include = "**/.gitignore"
cmd = [ "omegasort", "--sort=path" ]
lint_flags = "--check"
tidy_flags = "--in-place"
ok_exit_codes = 0
lint_failure_exit_codes = 1
expect_stderr = true
